# Example mqtt.yaml entry
sensor:
  - device:
      name: "EB3AXXXXXXXXXXXX"
      model: "EB3A"
      manufacturer: "Bluetti"
      identifiers: 
        - "XXXXXXXXXXXX"
    name: "Total Battery Percentage"
    unique_id: "EB3AXXXXXXXXXXXX/state/total_battery_percent"
    state_topic: "bluetti/EB3AXXXXXXXXXXXX/state/total_battery_percent"
    device_class: "battery"
    state_class: "measurement" # only if you want long term statistics 
    value_template: "{{ value }}"
  - device:
      name: "EB3AXXXXXXXXXXXX"
      model: "EB3A"
      manufacturer: "Bluetti"
      identifiers: 
        - "XXXXXXXXXXXX"
    name: "AC Input Power"
    unique_id: "EB3AXXXXXXXXXXXX/state/ac_input_power"
    state_topic: "bluetti/EB3AXXXXXXXXXXXX/state/ac_input_power"
    device_class: "power"
    unit_of_measurement: "W"
    state_class: "measurement" # only if you want long term statistics 
    value_template: "{{ value }}"
  - device:
      name: "EB3AXXXXXXXXXXXX"
      model: "EB3A"
      manufacturer: "Bluetti"
      identifiers: 
        - "XXXXXXXXXXXX"
    name: "DC Input Power"
    unique_id: "EB3AXXXXXXXXXXXX/state/dc_input_power"
    state_topic: "bluetti/EB3AXXXXXXXXXXXX/state/dc_input_power"
    device_class: "power"
    unit_of_measurement: "W"
    state_class: "measurement" # only if you want long term statistics 
    value_template: "{{ value }}"
  - device:
      name: "EB3AXXXXXXXXXXXX"
      model: "EB3A"
      manufacturer: "Bluetti"
      identifiers: 
        - "XXXXXXXXXXXX"
    name: "AC Ouput Power"
    unique_id: "EB3AXXXXXXXXXXXX/state/ac_output_power"
    state_topic: "bluetti/EB3AXXXXXXXXXXXX/state/ac_output_power"
    device_class: "power"
    unit_of_measurement: "W"
    state_class: "measurement" # only if you want long term statistics 
    value_template: "{{ value }}"
  - device:
      name: "EB3AXXXXXXXXXXXX"
      model: "EB3A"
      manufacturer: "Bluetti"
      identifiers: 
        - "XXXXXXXXXXXX"
    name: "DC Ouput Power"
    unique_id: "EB3AXXXXXXXXXXXX/state/dc_output_power"
    state_topic: "bluetti/EB3AXXXXXXXXXXXX/state/dc_output_power"
    device_class: "power"
    unit_of_measurement: "W"
    state_class: "measurement" # only if you want long term statistics 
    value_template: "{{ value }}"
  - device:
      name: "EB3AXXXXXXXXXXXX"
      model: "EB3A"
      manufacturer: "Bluetti"
      identifiers: 
        - "XXXXXXXXXXXX"
    name: "Last Device Update"
    unique_id: "EB3AXXXXXXXXXXXX/state/device_lastMex"
    state_topic: "bluetti/EB3AXXXXXXXXXXXX/state/device"
    state_class: "measurement" # only if you want long term statistics 
    value_template: "{{ value_json.LastUpdate }}"
    # available if USE_TEMPERATURE_SENSOR == 1
  - device:
      name: "EB3AXXXXXXXXXXXX"
      model: "EB3A"
      manufacturer: "Bluetti"
      identifiers: 
        - "XXXXXXXXXXXX"
    name: "Temperature"
    unique_id: "EB3AXXXXXXXXXXXX/state/temperature"
    state_topic: "bluetti/EB3AXXXXXXXXXXXX/state/temperature"
    device_class: "temperature"
    unit_of_measurement: "C"
    state_class: "measurement" # only if you want long term statistics 
    value_template: "{{ value }}"
  - device:
      name: "EB3AXXXXXXXXXXXX"
      model: "EB3A"
      manufacturer: "Bluetti"
      identifiers: 
        - "XXXXXXXXXXXX"
    name: "Humidity"
    unique_id: "EB3AXXXXXXXXXXXX/state/humidity"
    state_topic: "bluetti/EB3AXXXXXXXXXXXX/state/humidity"
    device_class: "humidity"
    unit_of_measurement: "%"
    state_class: "measurement" # only if you want long term statistics 
    value_template: "{{ value }}"
    # available if USE_EXT_BAT == 1
  - device:
      name: "EB3AXXXXXXXXXXXX"
      model: "EB3A"
      manufacturer: "Bluetti"
      identifiers: 
        - "XXXXXXXXXXXX"
    name: "External Battery Voltage"
    unique_id: "EB3AXXXXXXXXXXXX/state/EXT_BAT_Voltage"
    state_topic: "bluetti/EB3AXXXXXXXXXXXX/state/EXT_BAT_Voltage"
    device_class: "voltage"
    unit_of_measurement: "V"
    state_class: "measurement" # only if you want long term statistics 
    value_template: "{{ value }}"

binary_sensor:
  - device:
      name: "EB3AXXXXXXXXXXXX"
      model: "EB3A"
      manufacturer: "Bluetti"
      identifiers: 
        - "XXXXXXXXXXXX"
    name: "Connection status"
    unique_id: "EB3AXXXXXXXXXXXX/state/device_status"
    state_topic: "bluetti/EB3AXXXXXXXXXXXX/state/device_status"
    value_template: "{{ value_json.BTconnected }}"
    payload_on: 1
    payload_off: 0


switch:
  - device:
      name: "EB3AXXXXXXXXXXXX"
      model: "EB3A"
      manufacturer: "Bluetti"
      identifiers:
        - "XXXXXXXXXXXX"
    name: "Ac Output Switch"
    unique_id: "EB3AXXXXXXXXXXXX/state/ac_output_on"
    state_topic: "bluetti/EB3AXXXXXXXXXXXX/state/ac_output_on"
    command_topic: "bluetti/EB3AXXXXXXXXXXXX/command/ac_output_on"
    payload_on: 1
    payload_off: 0
    state_on: 1
    state_off: 0
  - device:
      name: "EB3AXXXXXXXXXXXX"
      model: "EB3A"
      manufacturer: "Bluetti"
      identifiers:
        - "XXXXXXXXXXXX"
    name: "Dc Output Switch"
    unique_id: "EB3AXXXXXXXXXXXX/state/dc_output_on"
    state_topic: "bluetti/EB3AXXXXXXXXXXXX/state/dc_output_on"
    command_topic: "bluetti/EB3AXXXXXXXXXXXX/command/dc_output_on"
    payload_on: 1
    payload_off: 0
    state_on: 1
    state_off: 0
    # available if USE_EXT_BAT == 1
  - device:
      name: "EB3AXXXXXXXXXXXX"
      model: "EB3A"
      manufacturer: "Bluetti"
      identifiers:
        - "XXXXXXXXXXXX"
    name: "EXT Battery DC IN Switch"
    unique_id: "EB3AXXXXXXXXXXXX/state/BAT_PWM_SWITCH"
    state_topic: "bluetti/EB3AXXXXXXXXXXXX/state/BAT_PWM_SWITCH"
    command_topic: "bluetti/EB3AXXXXXXXXXXXX/command/BAT_PWM_SWITCH"
    payload_on: 1
    payload_off: 0
    state_on: 1
    state_off: 0
    # available ifdef RELAY_220_PIN
  - device:
      name: "EB3AXXXXXXXXXXXX"
      model: "EB3A"
      manufacturer: "Bluetti"
      identifiers:
        - "XXXXXXXXXXXX"
    name: "220V AC IN Switch"
    unique_id: "EB3AXXXXXXXXXXXX/state/220_RELAY"
    state_topic: "bluetti/EB3AXXXXXXXXXXXX/state/220_RELAY"
    command_topic: "bluetti/EB3AXXXXXXXXXXXX/command/220_RELAY"
    payload_on: 1
    payload_off: 0
    state_on: 1
    state_off: 0
